import { StyleSheet } from 'react-native';
import colors from '../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignSelf: 'center',
    // minHeight: 750,

    minHeight: 985,
    maxHeight: 985,

    width: 400,

    borderRadius: 30,
    // zIndex: 20,
  },

  headerOne: {
    // alignSelf: 'center',
    backgroundColor: '#000',
    height: 63,
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    // width: '100%',
  },
  header: {
    alignSelf: 'center',
    height: 65,
    width: '97%',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
  },

  phone: {
    height: '100%',
    width: '100%',
    justifyContent: 'space-around',
    backgroundColor: colors.white,
  },
  back: {
    position: 'absolute',
    height: 70,
    width: 70,
    left: 0,
    top: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },

  icon: { marginTop: '-20%' },
  title: {
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    left: 70,
    top: 0,
    marginTop: '-1%',
    width: '30%',
  },

  textTitle: {
    position: 'absolute',
    left: 5,
    top: 15,
    fontSize: 18,
    color: 'white',
    fontWeight: '500',
    width: '180%',
  },

  input: {
    width: '90%',
    borderRadius: 25,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: '#ffffff',
    padding: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.25,
    shadowRadius: 26,
    elevation: 14,
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: 30,
    marginBottom: 10,
  },

  inputTwo: {
    width: '90%',
    borderRadius: 25,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: '#ffffff',
    padding: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.25,
    shadowRadius: 26,
    elevation: 14,
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '70%',
    marginBottom: 10,
    position: 'absolute',
    alignSelf: 'center',
  },
  button: {
    zIndex: 80,
    width: '40%',
    height: '5%',
    justifyContent: 'center',
    // alignItems: 'center',
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: '#ffffff',
    padding: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.25,
    shadowRadius: 26,
    elevation: 14,

    marginLeft: 'auto',
    marginRight: 'auto',
  },
  buttondisabled: {
    zIndex: 80,
    width: '40%',
    height: '5%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: '#deac98de',
    padding: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.25,
    shadowRadius: 26,
    elevation: 14,

    marginLeft: 'auto',
    marginRight: 'auto',
  },

  TextAdd: {
    color: colors.primary,
    paddingLeft: 5,
    paddingRight: 5,
    alignSelf: 'center',
    fontSize: 20,
    fontWeight: 'bold',
    // marginTop: '0.7%',
  },

  search: {
    color: colors.primary,
    paddingLeft: 5,
    paddingRight: 5,
    alignSelf: 'center',
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: '0.7%',
  },

  searchDisable: {
    color: '#9a788ccf',
    paddingLeft: 5,
    paddingRight: 5,
    alignSelf: 'center',
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: '0.7%',
  },
  ellipse: {
    position: 'relative',
    alignSelf: 'center',
    width: '32.2%',
    height: '27%',
    marginTop: '-35%',
    borderTopLeftRadius: 900,
    borderTopRightRadius: 900,
    borderBottomLeftRadius: 263,
    borderBottomRightRadius: 263,
    transform: [{ scaleX: 3 }],
  },
  // elipseView: { zIndex: 10, },
  buttonAdd: {
    zIndex: 80,
    width: '70%',
    height: '6%',
    alignItems: 'center',
    marginTop: '90%',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: '#ffffff',
    padding: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.25,
    shadowRadius: 26,
    elevation: 14,

    marginLeft: 'auto',
    marginRight: 'auto',
  },
  buttonAddDisable: {
    zIndex: 80,

    width: '70%',
    height: '6%',
    alignItems: 'center',
    marginTop: '90%',

    borderRadius: 20,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: '#deac98de',
    padding: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.25,
    shadowRadius: 26,
    elevation: 14,

    marginLeft: 'auto',
    marginRight: 'auto',
  },
  msgText: {
    position: 'absolute',
    alignSelf: 'center',
    marginTop: '85%',
  },
  msgTextUser: {
    position: 'absolute',
    alignSelf: 'center',
    textAlign: 'center',
    marginTop: '85%',
  },
});
