import { StyleSheet } from 'react-native';
import colors from '../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
    padding: 10,
    overflow: 'hidden',
    zIndex: 0,
  },
  inputContainer: {
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
  },
  prueba: {
    height: 200,
    width: 200,
    backgroundColor: 'red',
  },
  prueba1: {
    height: 200,
    width: 200,
    backgroundColor: 'blue',
  },
  prueba2: {
    height: 200,
    width: 200,
    backgroundColor: 'black',
  },
  text: {
    marginTop: 10,
    marginBottom: 10,
    color: 'grey',
    textAlign: 'center',
    fontSize: 20,
  },
  containerButton: {
    alignItems: 'center',
    width: 300,
    height: 100,
    zIndex: 30,
    marginBottom: -150,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  button: {
    zIndex: 80,
    width: '90%',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: '#ffffff',
    padding: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.25,
    shadowRadius: 26,
    elevation: 14,

    marginLeft: 'auto',
    marginRight: 'auto',
  },
  buttondisabled: {
    zIndex: 80,
    width: '90%',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: '#deac98de',
    padding: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.25,
    shadowRadius: 26,
    elevation: 14,

    marginLeft: 'auto',
    marginRight: 'auto',
  },
  ellipse: {
    position: 'relative',
    zIndex: 20,
    bottom: '-25%',
    marginTop: '-50%',
    left: '20%',
    width: '60%',
    height: '60%',
    borderRadius: 999,
    transform: [{ scaleX: 3 }],
  },
  header: {
    height: 75,
    width: '100%',
  },

  title: {
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    left: 70,
    top: 0,
    marginTop: '-0.3%',
    width: '30%',
  },

  textTitle: {
    position: 'absolute',
    left: 5,
    top: 15,
    fontSize: 20,
    color: 'white',
    fontWeight: '500',
    width: '180%',
  },
  back: {
    position: 'absolute',
    height: 70,
    width: 70,
    left: 0,
    top: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },

  icon: { marginTop: '-18%' },

  headerOne: { backgroundColor: '#000', height: 63 },
});
