import { StyleSheet } from 'react-native';
import colors from '../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
    padding: 10,
  },
  inputEmail: {
    borderRadius: 50,
    height: 45,
    borderWidth: 2,
    borderColor: '#FF6C5D',
    paddingVertical: 0,
    paddingLeft: 8,
    paddingRight: 8,
    marginTop: 10,
  },
  back: {
    position: 'absolute',
    left: -10,
    top: -15,
  },
  inputPassword: {
    borderRadius: 50,
    height: 45,
    borderWidth: 2,
    borderColor: '#FF6C5D',
    paddingVertical: 0,
    justifyContent: 'center',
    paddingLeft: 8,
    paddingRight: 8,
    marginTop: 30,
  },
  inputRegister: {
    borderRadius: 50,
    height: 45,
    borderWidth: 2,
    borderColor: '#FF6C5D',
    paddingVertical: 0,
    paddingLeft: 8,
    paddingRight: 8,
  },
  btn: {
    backgroundColor: 'blue',
  },
  img: {
    borderRadius: 50,
    width: 80,
    height: 80,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  registertwo: {
    width: 0,
    height: 0,
  },

  textError: {
    color: 'red',
  },
  birthdateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 48,
    borderRadius: 8,
    borderColor: 'grey',
    borderWidth: StyleSheet.hairlineWidth,
    padding: 8,
  },
  birthdateButtonText: { color: 'grey' },

  next: {
    // color: '#9a788ccf',
    // paddingLeft: 5,
    // paddingRight: 5,
    // alignSelf: 'center',
    // fontSize: 28,
    // fontWeight: 'bold',

    color: '#9a788ccf',
    paddingLeft: 5,
    paddingRight: 5,
    alignSelf: 'center',
    fontSize: 20,
    fontWeight: '700',
    justifyContent: 'center',
    marginTop: '-3%',
  },
  button: {
    width: '120%',
    alignItems: 'center',
    height: '50%',
    marginTop: '30%',
    marginLeft: '-11%',
    // marginBottom: 20,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: '#deac98de',
    padding: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.25,
    shadowRadius: 26,
    elevation: 14,

    // marginRight: '95%',
    // marginLeft: 'auto',
  },

  buttonRegister: {
    width: '120%',
    alignItems: 'center',
    height: '50%',
    marginTop: '55%',
    marginLeft: '-11%',
    // marginBottom: 20,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: '#fff',
    padding: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.25,
    shadowRadius: 26,
    elevation: 14,
  },

  setpOne: {
    marginTop: '20%',
  },

  ellipse: {
    position: 'relative',
    zIndex: 20,
    bottom: '-25%',
    marginTop: '-50%',
    left: '20%',
    width: '60%',
    height: '60%',
    borderRadius: 999,
    transform: [{ scaleX: 3 }],
  },
  btns: {
    width: 200,
    height: 100,
    zIndex: 30,
    marginLeft: 'auto',
    marginRight: 'auto',
  },

  ellipseTwo: {
    position: 'relative',
    zIndex: 20,
    bottom: '-25%',
    marginTop: '-50%',
    left: '20%',
    width: '60%',
    height: '60%',
    borderRadius: 999,
    transform: [{ scaleX: 3 }],
  },

  buttontwo: {
    width: '120%',
    alignItems: 'center',
    height: '50%',
    marginTop: '30%',
    marginLeft: '-11%',
    // marginBottom: 20,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: '#deac98de',
    padding: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.25,
    shadowRadius: 26,
    elevation: 14,
  },

  textTwo: {
    color: colors.primary,
    paddingLeft: 5,
    paddingRight: 5,
    alignSelf: 'center',
    fontSize: 18,
    fontWeight: '700',
    marginTop: '-3%',
  },
});
